# Update sampling frame

```{r}
mhq_watersurfaces_samplingunits <- read_vc(file = "mhq_watersurfaces_samplingunits", root = "../output")

```

```{r}
watersurfaces_hab <- read_watersurfaces_hab()
watersurfaces_hab_types <- watersurfaces_hab$watersurfaces_types %>%
  filter(! str_detect(type, "rbb")) %>%
  rename(code_watersurfaces = polygon_id, type_target = type)
```

```{r}

mhq_watersurfaces_samplingunits_3130 <- mhq_watersurfaces_samplingunits %>%
  filter(str_sub(type_target, 1, 4) == "3130")

mhq_watersurfaces_samplingunits_new <-  watersurfaces_hab_types %>%
  anti_join(mhq_watersurfaces_samplingunits, by = c("code_watersurfaces", "type_target")) %>%
  filter(!(code_watersurfaces %in% mhq_watersurfaces_samplingunits_3130$code_watersurfaces &
           type_target == "3130")) %>%
  filter(!str_detect(code_watersurfaces, "_v")) %>%
  mutate(scheme = ifelse(type_target == "2190_a", "HQ2190_aq", str_c("HQ", str_sub(type_target, 1, 4))),
         source_samplingunit = "watersurfaces_hab_v4")

mhq_watersurfaces_samplingunits_update <- mhq_watersurfaces_samplingunits %>%
  mutate(scheme = ifelse(type_target == "2190_a", "HQ2190_aq", str_c("HQ", str_sub(type_target, 1, 4)))) %>%
  bind_rows(mhq_watersurfaces_samplingunits_new)
  
```


```{r}
grts_master <- read_GRTSmh()

watersurfaces_refpoints <- read_vc(file = "watersurfaces_refpoints", root = "../output")

refpoints_new <- watersurfaces_hab$watersurfaces_polygons %>%
  rename(code_watersurfaces = polygon_id) %>%
  anti_join(watersurfaces_refpoints, by = "code_watersurfaces") %>%
  semi_join(mhq_watersurfaces_samplingunits_new, by = "code_watersurfaces") %>%
  st_point_on_surface() %>%
  mutate(grts_ranking = grts_master[as(., "Spatial")],
         in_object = TRUE)

refpoints_new <- refpoints_new %>%
  st_drop_geometry() %>%
  mutate(x = st_coordinates(refpoints_new)[,1],
         y = st_coordinates(refpoints_new)[,2]) %>%
  select(code_watersurfaces, grts_ranking, in_object, x, y)
    
watersurfaces_refpoints_update <- watersurfaces_refpoints %>%
  bind_rows(refpoints_new)

watersurfaces_refpoints_update %>%
  write_vc("watersurfaces_refpoints", "../output", sorting = c("grts_ranking", "code_watersurfaces"))

```

```{r}
mhq_watersurfaces_assessments <- read_vc(file = "mhq_watersurfaces_assessments", root = "../output")

mhq_type_observed <- mhq_watersurfaces_assessments %>%
  distinct(code_watersurfaces, type_observed_all) %>%
  mutate(assessed = TRUE,
         type_observed_all = ifelse(is.na(type_observed_all), "gh", type_observed_all))

watersurfaces_samplingunits <- mhq_watersurfaces_samplingunits_update %>%
  left_join(mhq_type_observed, by = "code_watersurfaces") %>%
  mutate(contains_type = str_detect(type_observed_all, type_target),
         assessed = ifelse(is.na(assessed), FALSE, assessed)) %>%
  select(code_watersurfaces, type_target, source_samplingunit, assessed, contains_type)

watersurfaces_hab_3130 <- watersurfaces_hab_types %>%
  filter(type_target == "3130")

watersurfaces_samplingunits_remove <- watersurfaces_samplingunits %>%
  filter(!assessed) %>%
  anti_join(watersurfaces_hab_types, by = c("code_watersurfaces", "type_target")) %>%
  filter(! (str_sub(type_target, 1,4) == "3130" & code_watersurfaces %in% watersurfaces_hab_3130$code_watersurfaces))

watersurfaces_samplingunits <- watersurfaces_samplingunits %>%
  anti_join(watersurfaces_samplingunits_remove, by = c("code_watersurfaces", "type_target")) %>%
  rename(type = type_target) %>%
  unique()

check <- watersurfaces_samplingunits %>%
  group_by(code_watersurfaces, type) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  filter(n > 1)

watersurfaces_samplingunits %>%
  write_vc("watersurfaces_samplingunits", root = "../output", sorting = c("code_watersurfaces", "type"))

```




